version: "3"
services:
    frontend:
        container_name: frontend
        build:
            context: ./front
            dockerfile: dockerfile
        image: frontend
        ports:
            - "3000:3000"
        volumes:
            - ./front:/app
        networks:
            - glob

    backend:
        container_name: backend
        build:
            context: ./back
            dockerfile: dockerfile
        image: backend
        ports:
            - "4000:4000"
        volumes:
            - ./back:/app
        networks:
            - glob

    postgres:
        image: postgres:13-alpine
        ports:
        - 5432:5432
        env_file:
        - .env
        volumes:
        - postgres:/var/lib/postgresql/data
        networks:
        - glob

volumes:
   postgres:
      name: postgres-volume

networks:
   glob:
